### PR TITLE
vyatta-op-dhcp-server: tidy up output on "show dhcp server leases"

### PR DESCRIPTION
**Pull request by alexharpin**
Tidy up the output of both "show dhcp server leases" and "show dhcp
server statistics".  This allows a little more room for those of us
that use a longer dhcp pool name and keeps the format style the same
across the two.

Bug #296 http://bugzilla.vyos.net/show_bug.cgi?id=296

### CODE REVIEW

**Comment by dmbaturin** [comment]
Please specify the bug number in commit message.
Also, whenever possible, please avoid mixing logic changes and formatting changes in one commit, it makes the diff harder to read.

**Comment by dmbaturin** [comment]
Ah, wait, you did specify the bug number. I usually look for it where I do it myself ("Bug #XXX: fix something" in the first line), but this works too. :)

**Comment by alexharpin** [comment]
Sorry, just got in the habit of putting in the module I'm doing the patch for and then a brief description as the title, then adding the the bug number later, as I tend to write the description, submit the bug, then commit the patch and include the bug number in the commit message.

Forgot I'd done the formatting changes with that one, just force of habit getting everything at the same indent level.

**Comment by dmbaturin** [comment]
Yeah, theres're a lot of style inconsistecies in vyos code. I just prefer to keep style cleanups in separate commits, unless logic change and style changes are in the same lines, to keep the diffs clean and to ensure reverts, be they needed, do not reverse more than they should.

**Comment by alexharpin** [comment]
No problem, I'll keep that in mind for future commits.  While I think on it, do you want style changes logging as bugs or will a simple commit (with appropriate message) be enough?  Also, which would work the best for you, style change commit first and logic commit second (if it touches the same file but not the same lines), the other way round, or doesn't really matter?  Just to make it easier for you to keep track of really.

**Comment by dmbaturin** [comment]
Style changes hardly require a bug, since they have no effect on the system behaviour.
The order doesn't really matter, the only important thing is to keep them separate.

**Comment by alexharpin** [comment]
Cheers, that's what I thought, just wanted to check and make life easier for you.

**Pull request merged**
